name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/android-sdk

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install Android SDK Command Line Tools
      run: |
        mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools/latest
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools/* ${ANDROID_SDK_ROOT}/cmdline-tools/latest/
        rm -r cmdline-tools cmdline-tools.zip

    - name: Add SDK tools to PATH
      run: echo "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Install SDK packages
      run: |
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Accept SDK licenses
      run: yes | sdkmanager --licenses

    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace --info

    - name: Verify APK
      run: ls -l app/build/outputs/apk/debug/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
