name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/android-sdk

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Install Android SDK Command Line Tools
      run: |
        sudo mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT
        sudo wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        sudo unzip cmdline-tools.zip -d cmdline-tools
        sudo rm cmdline-tools.zip

    - name: Add SDK tools to PATH
      run: echo "$ANDROID_SDK_ROOT/cmdline-tools/tools/bin" >> $GITHUB_PATH

    - name: Install SDK packages
      run: |
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Accept SDK licenses
      run: yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace --info

    - name: Verify APK
      run: ls -l app/build/outputs/apk/debug/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
